cs:

config:
	git config -l

count:
	ls -al | grep "RunNetflix.in"   | wc -l
	ls -al | grep "RunNetflix.out"  | wc -l
	ls -al | grep "TestNetflix.py"  | wc -l
	ls -al | grep "TestNetflix.out" | wc -l
	ls -al | grep "\.json"          | wc -l
	ls -al | grep "\.txt"           | wc -l

log:
	git log

pull:
	git pull

status:
	git branch
	git remote
	git status
