cs:

config:
	git config -l

count:
	ls -al | grep "apiary.apib" | wc -l
	ls -al | grep "models.py"   | wc -l
	ls -al | grep "tests.py"    | wc -l
	ls -al | grep "tests.out"   | wc -l

log:
	git log

pull:
	git pull

status:
	git branch
	git remote
	git status
